### ISSUE TITLE
It is recommended to support lower nodejs versions, for example, nodejs 10/12, nodejs 15 is really new

### ISSUE THREAD

**Issue by rxliuli** [fliegwerk/fliegdoc#20]

**Comment by pklaschka** [comment]
Thank you for opening this issue.

To be honest, since this started out as an "internal" project (i.e., a thing a couple of friends and I started) just a couple of days ago, I didn't really put a huge focus on supporting earlier versions of NodeJS (as it was, and, to an extent, still is, in a proof-of-concept stage, even though we already use it in production).

I do, however, plan to support Node v14 (which, after all, is currently the LTS version) in the near future. From a quick scan, I think the only thing I have to do to add proper support is to replace the `string.replaceAll` calls.

Thanks for reporting this, I'll do my best to add support for the current LTS version (v14) as soon as possible. I currently don't know if I still want to support v12, which, after all, is still in maintenance.

@fussel178 Do you think we can/should support Node versions older than v14?

@rxliuli Thanks again 🙂

**Comment by pklaschka** [comment]
I'll also mark this as a good first issue.

As far as I can tell, it's only changing the `engine` in the `package.json` and the `replaceAll` calls on strings that stop this project from being compatible with older versions (or, at least, v14).

Otherwise, I'll hopefully find the time to do it myself in a couple of days. 🙂

**Comment by rxliuli** [comment]
> Thank you for opening this issue.
> 
> To be honest, since this started out as an "internal" project (i.e., a thing a couple of friends and I started) just a couple of days ago, I didn't really put a huge focus on supporting earlier versions of NodeJS (as it was, and, to an extent, still is, in a proof-of-concept stage, even though we already use it in production).
> 
> I do, however, plan to support Node v14 (which, after all, is currently the LTS version) in the near future. From a quick scan, I think the only thing I have to do to add proper support is to replace the `string.replaceAll` calls.
> 
> Thanks for reporting this, I'll do my best to add support for the current LTS version (v14) as soon as possible. I currently don't know if I still want to support v12, which, after all, is still in maintenance.
> 
> @fussel178 Do you think we can/should support Node versions older than v14?
> 
> @rxliuli Thanks again 🙂

Yes, but lower nodejs version support is also very simple, why not? If you want to use it in production, you may not be able to choose the nodejs version sometimes. For example, the previous code cannot be easily upgraded. We currently use nodejs 12 because a native dependency only supports nodejs 12 and below. . .
In fact, most of the time we choose the nodejs version in the production environment is to observe the choice of large companies, such as aws (https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported .nodejs), not for upgrading

**Comment by pklaschka** [comment]
@rxliuli I agree.

If (and I believe, as you say, that we will) we find that it's no problem for us to support older versions than v14, we probably will do that.

v14, to me, is just the must-have supported version. I hope that we can support even older versions without sacrificing the project's maintainability or readability (which are our main priorities). If so, I won't "artificially" (by setting the `engine` to something higher) stop supporting these versions.

However, we won't have the capacity to support, say, five major Node versions on Windows, Linux, and macOS, since we don't have enough time/people to do that. This means that we'd have it so that it's possible to use these versions, but no "official support" or high priority could be given to issues on these lower versions.

(I have never worked with the API side of `typescript`, or here, through the abstraction of `ts-morph`, before, which is why I'm unable to assess whether or not it's easy to support these lower versions)

**Comment by fussel178** [comment]
For most projects, I think, it's useful to support Node versions down to v12 because many projects currently using a  LTS version of Node (see https://nodejs.org/en/about/releases/). (and Node v12 support goes for another year)
However, I am not sure about supporting Node.js v10 because its estimated EOL later this year.
@pklaschka Do you think, it's worth the effort?
