### ISSUE TITLE
Unable to close search on mobile

### ISSUE THREAD

**Issue by Gerrit0** [fliegwerk/fliegdoc#26]
**Describe the bug**
As titled, when loading the docs on mobile, as soon as I scroll down the search pops up in the middle of the screen and cannot be closed.

**To Reproduce**

1. Go to https://fliegwerk.github.io/fliegdoc/fliegdoc/#DEFAULT_CONFIG
1. Scroll down slightly
1. See error

**Expected behavior**
Search should only show up when clicking on a search icon.

**Screenshots**

![image](https://user-images.githubusercontent.com/19329837/104925341-f313f700-595b-11eb-93f9-4fe069a589a2.png)

**Smartphone:**

- OS: iOS
- Browser safari
- Version 14.3

**Comment by pklaschka** [comment]
Thanks for reporting this. I'll look into supporting mobile devices with the search as soon as possible.

Overall, mobile support is a topic that needs a lot of improvement in the near future. 

Since, only a couple of days ago, this started as an internal project without any consideration on responsiveness, etc. (since internally, we only use it on Desktop), we didn't even think about search on mobile devices, to be honest (having it work "as good" as it does now is just a side-effect of using some semi-random CSS framework in the proof of concept stage 😅 ).

I wasn't able to replicate this in a desktop browser (with mobile device emulation), but we'll definitely look into it (while personally, I don't own an iPhone, I think I know someone who might be able to debug this with me).

Again: Thanks for pointing this out, we're going to look into it 🙂

**Comment by pklaschka** [comment]
I believe the issue is Safari's missing support for the `<dialog>` element. This, theoretically, makes this an issue of https://github.com/fliegwerk/search-popup, but let's track this here for better discoverability.
